dynamic_columns:
- joint_0_coulomb_friction_coeff
- joint_0_viscous_friction_coeff
- joint_1_coulomb_friction_coeff
- joint_1_viscous_friction_coeff
- joint_2_coulomb_friction_coeff
- joint_2_viscous_friction_coeff
- joint_3_coulomb_friction_coeff
- joint_3_viscous_friction_coeff
- joint_4_coulomb_friction_coeff
- joint_4_viscous_friction_coeff
- joint_5_coulomb_friction_coeff
- joint_5_viscous_friction_coeff
- link_1_izz
- link_2_com_z
- link_2_ixx
- link_2_iyy
- link_2_izz
- link_2_mass
- link_3_com_z
- link_3_ixx
- link_3_iyy
- link_3_izz
- link_3_mass
- link_4_com_z
- link_4_ixx
- link_4_iyy
- link_4_izz
- link_4_mass
- link_5_com_z
- link_5_ixx
- link_5_iyy
- link_5_izz
- link_5_mass
- link_6_com_z
- link_6_ixx
- link_6_iyy
- link_6_izz
- link_6_mass
constant_columns:
- link_1_com_x
- link_1_com_y
- link_1_com_z
- link_1_ixx
- link_1_ixy
- link_1_ixz
- link_1_iyy
- link_1_iyz
- link_1_mass
- link_2_com_x
- link_2_com_y
- link_2_ixy
- link_2_ixz
- link_2_iyz
- link_3_com_x
- link_3_com_y
- link_3_ixy
- link_3_ixz
- link_3_iyz
- link_4_com_x
- link_4_com_y
- link_4_ixy
- link_4_ixz
- link_4_iyz
- link_5_com_x
- link_5_com_y
- link_5_ixy
- link_5_ixz
- link_5_iyz
- link_6_com_x
- link_6_com_y
- link_6_ixy
- link_6_ixz
- link_6_iyz
