dynamic_columns:
- time
- index
- joint_0_position
- joint_0_velocity
- joint_0_torque
- joint_0_link_3_dx_dj
- joint_0_link_3_dy_dj
- joint_0_link_4_dx_dj
- joint_0_link_4_dy_dj
- joint_0_link_5_dx_dj
- joint_0_link_5_dy_dj
- joint_0_link_6_dx_dj
- joint_0_link_6_dy_dj
- joint_1_position
- joint_1_velocity
- joint_1_torque
- joint_1_link_2_dwx_dj
- joint_1_link_2_dwy_dj
- joint_1_link_3_dx_dj
- joint_1_link_3_dy_dj
- joint_1_link_3_dz_dj
- joint_1_link_3_dwx_dj
- joint_1_link_3_dwy_dj
- joint_1_link_4_dx_dj
- joint_1_link_4_dy_dj
- joint_1_link_4_dz_dj
- joint_1_link_4_dwx_dj
- joint_1_link_4_dwy_dj
- joint_1_link_5_dx_dj
- joint_1_link_5_dy_dj
- joint_1_link_5_dz_dj
- joint_1_link_5_dwx_dj
- joint_1_link_5_dwy_dj
- joint_1_link_6_dx_dj
- joint_1_link_6_dy_dj
- joint_1_link_6_dz_dj
- joint_1_link_6_dwx_dj
- joint_1_link_6_dwy_dj
- joint_2_position
- joint_2_velocity
- joint_2_torque
- joint_2_link_3_dwx_dj
- joint_2_link_3_dwy_dj
- joint_2_link_4_dx_dj
- joint_2_link_4_dy_dj
- joint_2_link_4_dz_dj
- joint_2_link_4_dwx_dj
- joint_2_link_4_dwy_dj
- joint_2_link_5_dx_dj
- joint_2_link_5_dy_dj
- joint_2_link_5_dz_dj
- joint_2_link_5_dwx_dj
- joint_2_link_5_dwy_dj
- joint_2_link_6_dx_dj
- joint_2_link_6_dy_dj
- joint_2_link_6_dz_dj
- joint_2_link_6_dwx_dj
- joint_2_link_6_dwy_dj
- joint_3_position
- joint_3_velocity
- joint_3_torque
- joint_3_link_4_dwx_dj
- joint_3_link_4_dwy_dj
- joint_3_link_4_dwz_dj
- joint_3_link_5_dwx_dj
- joint_3_link_5_dwy_dj
- joint_3_link_5_dwz_dj
- joint_3_link_6_dx_dj
- joint_3_link_6_dy_dj
- joint_3_link_6_dz_dj
- joint_3_link_6_dwx_dj
- joint_3_link_6_dwy_dj
- joint_3_link_6_dwz_dj
- joint_4_position
- joint_4_velocity
- joint_4_torque
- joint_4_link_5_dwx_dj
- joint_4_link_5_dwy_dj
- joint_4_link_5_dwz_dj
- joint_4_link_6_dx_dj
- joint_4_link_6_dy_dj
- joint_4_link_6_dz_dj
- joint_4_link_6_dwx_dj
- joint_4_link_6_dwy_dj
- joint_4_link_6_dwz_dj
- joint_5_position
- joint_5_velocity
- joint_5_torque
- joint_5_link_6_dwx_dj
- joint_5_link_6_dwy_dj
- joint_5_link_6_dwz_dj
constant_columns:
- joint_0_link_1_dx_dj
- joint_0_link_1_dy_dj
- joint_0_link_1_dz_dj
- joint_0_link_1_dwx_dj
- joint_0_link_1_dwy_dj
- joint_0_link_1_dwz_dj
- joint_0_link_2_dx_dj
- joint_0_link_2_dy_dj
- joint_0_link_2_dz_dj
- joint_0_link_2_dwx_dj
- joint_0_link_2_dwy_dj
- joint_0_link_2_dwz_dj
- joint_0_link_3_dz_dj
- joint_0_link_3_dwx_dj
- joint_0_link_3_dwy_dj
- joint_0_link_3_dwz_dj
- joint_0_link_4_dz_dj
- joint_0_link_4_dwx_dj
- joint_0_link_4_dwy_dj
- joint_0_link_4_dwz_dj
- joint_0_link_5_dz_dj
- joint_0_link_5_dwx_dj
- joint_0_link_5_dwy_dj
- joint_0_link_5_dwz_dj
- joint_0_link_6_dz_dj
- joint_0_link_6_dwx_dj
- joint_0_link_6_dwy_dj
- joint_0_link_6_dwz_dj
- joint_1_link_1_dx_dj
- joint_1_link_1_dy_dj
- joint_1_link_1_dz_dj
- joint_1_link_1_dwx_dj
- joint_1_link_1_dwy_dj
- joint_1_link_1_dwz_dj
- joint_1_link_2_dx_dj
- joint_1_link_2_dy_dj
- joint_1_link_2_dz_dj
- joint_1_link_2_dwz_dj
- joint_1_link_3_dwz_dj
- joint_1_link_4_dwz_dj
- joint_1_link_5_dwz_dj
- joint_1_link_6_dwz_dj
- joint_2_link_1_dx_dj
- joint_2_link_1_dy_dj
- joint_2_link_1_dz_dj
- joint_2_link_1_dwx_dj
- joint_2_link_1_dwy_dj
- joint_2_link_1_dwz_dj
- joint_2_link_2_dx_dj
- joint_2_link_2_dy_dj
- joint_2_link_2_dz_dj
- joint_2_link_2_dwx_dj
- joint_2_link_2_dwy_dj
- joint_2_link_2_dwz_dj
- joint_2_link_3_dx_dj
- joint_2_link_3_dy_dj
- joint_2_link_3_dz_dj
- joint_2_link_3_dwz_dj
- joint_2_link_4_dwz_dj
- joint_2_link_5_dwz_dj
- joint_2_link_6_dwz_dj
- joint_3_link_1_dx_dj
- joint_3_link_1_dy_dj
- joint_3_link_1_dz_dj
- joint_3_link_1_dwx_dj
- joint_3_link_1_dwy_dj
- joint_3_link_1_dwz_dj
- joint_3_link_2_dx_dj
- joint_3_link_2_dy_dj
- joint_3_link_2_dz_dj
- joint_3_link_2_dwx_dj
- joint_3_link_2_dwy_dj
- joint_3_link_2_dwz_dj
- joint_3_link_3_dx_dj
- joint_3_link_3_dy_dj
- joint_3_link_3_dz_dj
- joint_3_link_3_dwx_dj
- joint_3_link_3_dwy_dj
- joint_3_link_3_dwz_dj
- joint_3_link_4_dx_dj
- joint_3_link_4_dy_dj
- joint_3_link_4_dz_dj
- joint_3_link_5_dx_dj
- joint_3_link_5_dy_dj
- joint_3_link_5_dz_dj
- joint_4_link_1_dx_dj
- joint_4_link_1_dy_dj
- joint_4_link_1_dz_dj
- joint_4_link_1_dwx_dj
- joint_4_link_1_dwy_dj
- joint_4_link_1_dwz_dj
- joint_4_link_2_dx_dj
- joint_4_link_2_dy_dj
- joint_4_link_2_dz_dj
- joint_4_link_2_dwx_dj
- joint_4_link_2_dwy_dj
- joint_4_link_2_dwz_dj
- joint_4_link_3_dx_dj
- joint_4_link_3_dy_dj
- joint_4_link_3_dz_dj
- joint_4_link_3_dwx_dj
- joint_4_link_3_dwy_dj
- joint_4_link_3_dwz_dj
- joint_4_link_4_dx_dj
- joint_4_link_4_dy_dj
- joint_4_link_4_dz_dj
- joint_4_link_4_dwx_dj
- joint_4_link_4_dwy_dj
- joint_4_link_4_dwz_dj
- joint_4_link_5_dx_dj
- joint_4_link_5_dy_dj
- joint_4_link_5_dz_dj
- joint_5_link_1_dx_dj
- joint_5_link_1_dy_dj
- joint_5_link_1_dz_dj
- joint_5_link_1_dwx_dj
- joint_5_link_1_dwy_dj
- joint_5_link_1_dwz_dj
- joint_5_link_2_dx_dj
- joint_5_link_2_dy_dj
- joint_5_link_2_dz_dj
- joint_5_link_2_dwx_dj
- joint_5_link_2_dwy_dj
- joint_5_link_2_dwz_dj
- joint_5_link_3_dx_dj
- joint_5_link_3_dy_dj
- joint_5_link_3_dz_dj
- joint_5_link_3_dwx_dj
- joint_5_link_3_dwy_dj
- joint_5_link_3_dwz_dj
- joint_5_link_4_dx_dj
- joint_5_link_4_dy_dj
- joint_5_link_4_dz_dj
- joint_5_link_4_dwx_dj
- joint_5_link_4_dwy_dj
- joint_5_link_4_dwz_dj
- joint_5_link_5_dx_dj
- joint_5_link_5_dy_dj
- joint_5_link_5_dz_dj
- joint_5_link_5_dwx_dj
- joint_5_link_5_dwy_dj
- joint_5_link_5_dwz_dj
- joint_5_link_6_dx_dj
- joint_5_link_6_dy_dj
- joint_5_link_6_dz_dj
